name: allure-report
on:
    push:
        branches:
            - master
jobs:
    start-app:
        runs-on: ubuntu-latest
        container:
            image: vmaksimenko/bulldoggy-reminders-app
            ports:
                - 8000

    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cypress install
              uses: cypress-io/github-action@v5

            - name: Upload Allure Results
              uses: actions/upload-artifact@v2
              with:
                  name: allure-results
                  path: allure-results
